### ISSUE TITLE
Validate_cmd causing issues

### ISSUE THREAD

**Issue by cdenneen** [fraenki/puppet-proftpd#10]
@fraenki noticing odd behavior that I'm not sure where issue lies. It might not be your module and might be a puppet bug but wanted to reference.

If you enable module loading (let's use the user example given in #8):
```yaml
---
proftpd::load_modules:
  sql:
    order: 1
  sql_mysql:
    order: 2
  quotatab:
    order: 3
  quotatab_sql:
    order: 4
  rewrite:
    order: 5
```
The validate_cmd complains on initial provision that it can't find the Included modules.conf but in looking at your config.pp it clearly states that modules.conf is before proftpd::config because of just this exact reason.
It's almost like it's not honoring that before statement?

```puppet
==> default: Info: Computing checksum on file /etc/proftpd.conf
==> default: Info: /Stage[main]/Proftpd::Config/File[/etc/proftpd.conf]: Filebucketed /etc/proftpd.conf to puppet with sum 739256bad808470546c286093a2c1d34
==> default: Debug: Executing: '/usr/sbin/proftpd -t -c /etc/proftpd.conf20160304-4276-iney4d'
==> default: Notice: /Stage[main]/Proftpd::Config/File[/etc/proftpd.conf]/mode: mode changed '0640' to '0644'
==> default: Debug: Class[Proftpd::Config]: Resource is being skipped, unscheduling all events
==> default: Info: Class[Proftpd::Config]: Unscheduling all events on Class[Proftpd::Config]
==> default: Debug: Class[Proftpd::Service]: Resource is being skipped, unscheduling all events
==> default: Notice: /Stage[main]/Proftpd::Service/Service[proftpd]: Dependency File[/etc/proftpd.conf] has failures: true
==> default: Debug: /Stage[main]/Proftpd::Service/Service[proftpd]: Resource is being skipped, unscheduling all events
==> default: Info: /Stage[main]/Proftpd::Service/Service[proftpd]: Unscheduling all events on Service[proftpd]
==> default: Debug: Class[Proftpd::Service]: Resource is being skipped, unscheduling all events
==> default: Error: Execution of '/usr/sbin/proftpd -t -c /etc/proftpd.conf20160304-4276-iney4d' returned 1: Checking syntax of configuration file
==> default: 2016-03-04 12:47:29,201 localhost.localdomain proftpd[5663]: warning: unable to include '/etc/proftpd/modules.conf': No such file or directory
==> default: 2016-03-04 12:47:29,201 localhost.localdomain proftpd[5663]: fatal: unknown configuration directive 'SQLBackend' on line 35 of '/etc/proftpd.conf20160304-4276-iney4d'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/execution.rb:216:in `execute'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/file.rb:804:in `block in write'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:388:in `replace_file'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/file.rb:798:in `write'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/file/content.rb:154:in `sync'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:209:in `sync'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:134:in `sync_if_needed'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:89:in `block in perform_changes'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:88:in `each'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:88:in `perform_changes'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:20:in `evaluate'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:204:in `apply'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:220:in `eval_resource'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:147:in `call'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:147:in `block (2 levels) in evaluate'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:292:in `block in thinmark'
==> default: /opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:291:in `thinmark'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:147:in `block in evaluate'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:118:in `traverse'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:138:in `evaluate'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:178:in `block in apply'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:153:in `with_destination'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:107:in `as_logging_destination'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:177:in `apply'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:119:in `block in apply_catalog'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:129:in `block in benchmark'
==> default: /opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:128:in `benchmark'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:118:in `apply_catalog'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:228:in `run_internal'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:134:in `block in run'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:223:in `override'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:133:in `run'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:343:in `apply_catalog'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:274:in `block in main'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:223:in `override'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:225:in `main'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:170:in `run_command'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `block in run'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:446:in `exit_on_fail'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `run'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:128:in `run'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
==> default: /opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
==> default: Error: /Stage[main]/Proftpd::Config/File[/etc/proftpd.conf]/content: change from {md5}739256bad808470546c286093a2c1d34 to {md5}17b7ca200d22fcc798ce4e5f63c8696f failed: Execution of '/usr/sbin/proftpd -t -c /etc/proftpd.conf20160304-4276-iney4d' returned 1: Checking syntax of configuration file
==> default: 2016-03-04 12:47:29,201 localhost.localdomain proftpd[5663]: warning: unable to include '/etc/proftpd/modules.conf': No such file or directory
==> default: 2016-03-04 12:47:29,201 localhost.localdomain proftpd[5663]: fatal: unknown configuration directive 'SQLBackend' on line 35 of '/etc/proftpd.conf20160304-4276-iney4d'
==> default: Warning: /Stage[main]/Proftpd::Service/Service[proftpd]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Proftpd::Config/Concat[/etc/proftpd/modules.conf]/File[/etc/proftpd/modules.conf]/ensure: defined content as '{md5}19c94a6eedca04d2dce93f064387263c'
```

As you can see this is the source of the error:
```
Execution of '/usr/sbin/proftpd -t -c /etc/proftpd.conf20160304-4276-iney4d' returned 1: Checking syntax of configuration file
==> default: 2016-03-04 12:47:29,201 localhost.localdomain proftpd[5663]: warning: unable to include '/etc/proftpd/modules.conf': No such file or directory
```
And a few lines down it writes out the file:
```
==> default: Notice: /Stage[main]/Proftpd::Config/Concat[/etc/proftpd/modules.conf]/File[/etc/proftpd/modules.conf]/ensure: defined content as '{md5}19c94a6eedca04d2dce93f064387263c'
```

**Comment by fraenki** [comment]
@cdenneen I couldn't reproduce this, but my last commit should fix this. Please reopen if issue is not fixed for you.
